- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
    update_cache: true

- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item }}"
    state: present
    login_host: "{{ rds_host }}"
    login_user: "{{ rds_user }}"
    login_password: "{{ rds_password }}"
  loop: "{{ databases }}"