- name: Deploy project
  hosts: "{{ DEPLOY_HOST }}"
  become: yes
  roles:
    - deploy/core
  vars:
    image_name: "{{ IMAGE_NAME }}"
    app_port: "{{ APP_PORT }}"
    app_dir: "{{ APP_DIR }}"
    docker_username: "{{ DOCKER_USERNAME }}"
    docker_password: "{{ DOCKER_PASSWORD }}"