all:
  hosts:
    public:
      ansible_host: "{{ PUBLIC_IP }}"
    monitoring:
      ansible_host: "{{ MONITORING_IP }}"
    private:
      ansible_host: "{{ PRIVATE_IP }}"
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i {{ SSH_KEY_PATH }} -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ MONITORING_IP }}"
    internal:
      ansible_host: "{{ INTERNAL_IP }}"
      ansible_ssh_common_args: >
        -o ProxyCommand="ssh -i {{ SSH_KEY_PATH }} -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ MONITORING_IP }}"